
spring:
  application:
    name: desafio-votacao
  datasource:
    url: jdbc:postgresql://localhost:5432/votacaodb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always


logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: info
spring-doc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true

cpf:
  validador:
    url: http://localhost:8080
